# site settings
title: Zetryan Satria
subtitle: Sistem Informasi
email: zetryans@gmail.com
description: Hi, Saya Mahasiswa Uin Suska Riau Up<br /> Jurusan Sistem informasi Fakultas Sains dan Teknologi.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: Tampan, Pekanbaru
city: Pekanbaru
zip_code: 55555
country: Pekanbaru, Indonesia
phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: zetryansatria
github_url:github.com/zetryan
linkedin_url:linkedin.com/in/zetryan-satria-217081155/

# build settings
markdown: kramdown

sass:
  style: compressed
